### ISSUE TITLE
[Feature Request] Multi language support

### ISSUE THREAD

**Issue by Florencea** [Jasonnor/th-music-video-generator#13]
Could add i18n support for MV Generator UI or translations for each tracks. Thanks!

**Comment by hemisemidemipresent** [comment]
so I tried to use thcrap's song name translator thing which just happens to be nicely in one file: https://srv.thpatch.net/lang_en/themes.js

however, it turns out that some audio track numbers are off. e.g. th13.5:

this repo's database: `"audio/th13.5/A10. ハルトマンの妖怪少女.mp3"`
thcrap: `"th135_09": "Hartmann's Youkai Girl"`

**Comment by hemisemidemipresent** [comment]
@Florencea can this be reopened? The feature isnt implemented yet

**Comment by hemisemidemipresent** [comment]
Alright now time for the menus
